CREATE TABLE OBES.USER (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(20) NOT NULL,
    PHONE_NUMBER VARCHAR(15),
    CPF VARCHAR(12),
    BIRTH_DATE DATE,
    INSTITUTION_TYPE VARCHAR(15)
)

alter table obes.user add unique (email)